# ===================================================================
# MES 生产级 Redis 7.x 核心配置项
# ===================================================================

# 监听与安全
bind 0.0.0.0
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no

# 数据存放目录与文件名 (持久化挂载)
dir /data
dbfilename dump.rdb

# RDB 快照策略 (定期写入磁盘)
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

# 开启 AOF 实时持久化 (防止断电丢失最近操作数据)
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# 内存上限控制与淘汰策略
maxmemory 1024mb
maxmemory-policy volatile-lru
